//Seleciona apenas um elemento
// const addUserText = document.getElementById('add-user')

// const myform = document.querySelector('.container #my-form')
// console.log(myform)

//Selecionar multiplos elementos
// const allItems = document.querySelectorAll(".items .item")
// console.log(allItems)
// console.log(allItems[0])

// const allItems = document.getElementsByClassName("item")
// console.log(allItems);

const allItems = document.getElementsByTagName('li');
console.log(allItems)

//Sempre utilizar o querySelectorAll
//getElementsByClassName e getElementsByTagName nao utiizar
